import { type NextPage } from "next";
import Head from "next/head";
import { useUser, SignInButton } from "@clerk/nextjs";
import { RouterOutputs, api } from "~/utils/api";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";
import { LoadingPage } from "~/components/loading";
dayjs.extend(relativeTime);


const CreatePostWizard = () => {
  const { user } = useUser();
  console.log("user", user)
  if (!user) return null;

  return (
    <div className="flex w-full gap-3">
      <div>
        <Image
          alt="Profile Image"
          className="rounded-full w-12 h-12"
          src={user.profileImageUrl}
          width={48}
          height={48}
        />
      </div>
      <input
        placeholder="Write some posts"
        className="bg-transparent grow outline-none"
      />
    </div>
  )
}

type PostWithUser = RouterOutputs["posts"]["getAll"][number];
const PostView = (props: PostWithUser) => {

  const { post, author } = props;

  return (
    <div
      key={post.id}
      className="flex p-4 border-b border-slate-400 gap-3"
    >
      <Image
        src={author.profileImageUrl}
        alt="Profile Image"
        className="rounded-full w-12 h-12"
        width={48}
        height={48}
      />
      <div className="flex flex-col">
        <div className="flex text-slate-400 gap-2">
          <span>{`@${author.username}`}</span>
          <span className="font-slim">{`${dayjs(post.createdAt).fromNow()}`}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  )
}

const Home: NextPage = () => {

  const user = useUser();
  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <LoadingPage />;

  if (!data) return <div>No data available</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full h-full border-slate-400 md:max-w-2xl border-x">
          <div className="border-b border-slate-400 p-4 flex">
            {!user.isSignedIn && <div className="flex justify-center"><SignInButton /></div>}
            {user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {
              data?.map((fullPost, index) => (<PostView {...fullPost} key={index} />))
            }
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
