import { type NextPage } from "next";
import Head from "next/head";
import { useUser, SignInButton } from "@clerk/nextjs";

const SinglePostPage: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex h-screen justify-center">
                <div className="w-full h-full border-slate-400 md:max-w-2xl border-x">
                    id
                </div>
            </main>
        </>
    );
};

export default SinglePostPage;
